application: gapust
version: 1
runtime: python27
api_version: 1
threadsafe: true
#view_id: 'ga:109231694'

default_expiration: "30m"

env_variables:
  DEBUG: false

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"
- name: yaml
  version: "3.10"
- name: pycrypto
  version: "2.6"

handlers:
- url: /static
  static_dir: static/

- url: /.*
  script: main.app

builtins:
- deferred: off
- appstats: off


#########################
skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak
- ^(.*/)?.*\.swp
- ^(.*/)?.*\.gitignore
- ^(.*/)?.*\.md
- ^(.*/)?gruntfile\.js
- ^(.*/)?package\.json
